@RESOURCE = solicitation/justification-type
@JUSTIFICATION_TYPE_ID = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe
@URL = {{HOST}}/{{RESOURCE}}


### Create Justification Type
# @name create-type
POST {{URL}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": "{{JUSTIFICATION_TYPE_ID}}",
  "name": "Tipo justificativa 2(anexo!!)",
  "shouldHaveAttachment": false
}

### List All Justification Types
# @name get-types
GET {{URL}}
Content-Type: application/json
Authorization: Bearer {{JWT}}


### Delete Justification Type 
# @name delete-type
DELETE {{URL}}/{{JUSTIFICATION_TYPE_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Update Justification Type 
# @name update-type 
PUT {{URL}}/{{JUSTIFICATION_TYPE_ID}}
rontent-Type: application/json
Authorization: Bearer {{JWT}}

{ 
  "shouldHaveAttachment": true
}
