@RESOURCE = solicitation/solicitations
@URL = {{HOST}}/{{RESOURCE}}
@COLLABORATOR_ID = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe


### Get all solicitations 
GET {{URL}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Create paid overtime solicitation
POST {{URL}}/paid-overtime
Content-Type: application/json
Authorization: Bearer {{JWT}}

{}

### Create Day Off Schedule Adjustment Solicitation
POST {{URL}}/day-off-schedule-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "dayOffSchedule": {
    "workdaysCount": 20,
    "daysOffCount": 10,
    "daysOff": ["2025-04-05", "2025-04-10", "2025-04-15"]
  }
}

### Create Time Punch Adjustment Solicitation
POST {{URL}}/time-punch-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "time": "23:00",
  "period": "FIRST_CLOCK_IN",
  "workdayLogDate": "2025-04-05",
  "reason": "FORGOTTEN"
}

### Create Day Off Solicitation

POST {{URL}}/day-off
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "dayOff": "2025-02-02"
}

### Create Excuse Absence Solicitation 

POST {{URL}}/excuse-absence
Content-Type: application/json 
Authorization: Bearer {{JWT}}

{
  "excuseAbsenceDate": "2025-02-02"
}


### Resolve Solicitation 
PATCH {{URL}}/resolve/b187861a-d331-4935-9cf1-2cdd078abc91
Content-Type: multipart/form-data
Authorization: Bearer {{JWT}}

{
  "status": "APPROVED",
  "solicitationType": "DAY_OFF"
}

### Get JustificationAttachmentUrl 
GET {{URL}}/attachments/809cba83-dbc4-4bbb-8cd6-9f19f4387f97-shrek.jpg
Authorization: Bearer {{JWT}}
