## Hour Bank - Transactions

@RESOURCE = hour-bank

@COLLABORATOR_ID = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe

### List transactions
GET {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}/transactions?startDate=2020-04-19&endDate=2026-04-27&operation=all
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Create transaction adjustment
POST {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}/transactions/adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "date": "2025-04-21",
  "operation": "credit",
  "time": "06:00"
}

### Get balance
GET {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}/balance
Content-Type: application/json
Authorization: Bearer {{JWT}}