# Auth - Accounts
@RESOURCE = auth/accounts
@ACCOUNT_ID = 5d8ea73e-0360-4b9e-a26b-5e94e167033e

## Get account
GET {{HOST}}/{{RESOURCE}}/{{ACCOUNT_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

## Enable account
PATCH {{HOST}}/{{RESOURCE}}/{{ACCOUNT_ID}}/enable
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

## Disable account
PATCH {{HOST}}/{{RESOURCE}}/{{ACCOUNT_ID}}/disable
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

## Update password
PATCH {{HOST}}/{{RESOURCE}}/{{ACCOUNT_ID}}/password
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "password": "654321"
}