# Auth - Accounts
@RESOURCE = auth/accounts
@COLLABORATOR_ID = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe

## Update account
PUT {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "account": {},
  "collaborator": {
    "name": "Johana Doe",
    "cpf": "12345678900",
    "workload": 6
  }
}

###

## Enable account
PATCH {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}/enable
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

## Disable account
PATCH {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}/disable
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

## Update password
PATCH {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}/password
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "password": "654321"
}