@RESOURCE = work-schedule/day-off-schedules
@COLLABORATOR_ID = 94f83dca-78ec-413e-8dc5-613288d3db94

### Get day off schedule
GET {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}


### Schedule days off 
GET {{HOST}}/{{RESOURCE}}
Content-Type: application/json
Authorization: Bearer {{JWT}}


### Update day off schedule
PUT {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "workdaysCount": 5,
  "daysOffCount": 2,
  "daysOff": ["2023-10-01", "2023-10-01"]
}