@RESOURCE = work-schedule/day-off-schedules
@COLLABORATOR_ID=9b1febb2-60e2-4369-8143-b69429bf4fb3

### Get day off schedule
GET {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}


### Schedule days off 
GET {{HOST}}/{{RESOURCE}}
Content-Type: application/json
Authorization: Bearer {{JWT}}


### Update day off schedule
PUT {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "workdaysCount": 5,
  "daysOffCount": 2,
  "daysOff": ["2023-10-01", "2023-10-01"]
}
