# Work schedule - Time Punch

@RESOURCE = work-schedule/time-punches

@TIME_PUNCH_ID = 99f14036-c26a-4f00-ae1b-9f8cce440a4e

## Punch time
PATCH {{HOST}}/{{RESOURCE}}/{{TIME_PUNCH_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "time": "22:00"
}

### 

## Adjust time punch log
PATCH {{HOST}}/{{RESOURCE}}/{{TIME_PUNCH_ID}}/adjust
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "time": "10:00",
  "period": "first_clock_in"
}