# Work schedule - Time Punch

@RESOURCE = work-schedule/time-punches

## Punch time
PATCH {{BASE_URL}}/{{RESOURCE}}/f6a4ab89-42b6-4d03-a204-cb9402bc86c4
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "time": "16:00:00"
}