@RESOURCE = work-schedule/workday-logs
@WORKDAY_LOG_ID = 352b2afc-85b4-4ac8-9f8e-839a9a6df1c1
@COLLABORATOR_Id = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe

## Get today workday log
GET {{HOST}}/{{RESOURCE}}/{{WORKDAY_LOG_ID}}/today
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

## Get collaborator history
GET {{HOST}}/{{RESOURCE}}/history/{{COLLABORATOR_Id}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

## Get collaboration sector history
GET {{HOST}}/{{RESOURCE}}/history?date=2024-04-14&page=1&collaboratorName=tam
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

## Get work time log
GET {{HOST}}/{{RESOURCE}}/work-time/{{COLLABORATOR_Id}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

## Close workday
PUT {{HOST}}/{{RESOURCE}}/close
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

## Punch time
PATCH {{HOST}}/{{RESOURCE}}/{{WORKDAY_LOG_ID}}/time-punch
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "time": "22:00"
}

### 

## Adjust time punch
PATCH {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_Id}}/time-punch/adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "time": "12:00",
  "period": "first_clock_in"
}


