# Hour Bank - Transactions

@RESOURCE = hour-bank

@COLLABORATOR_ID = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe

## List transactions
GET {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}/transactions
Content-Type: application/json
Authorization: Bearer {{JWT}}

## Calculate balance
GET {{HOST}}/{{RESOURCE}}/{{COLLABORATOR_ID}}/balance
Content-Type: application/json
Authorization: Bearer {{JWT}}