@RESOURCE = solicitation/justification-type
@JUSTIFICATION_TYPE_ID = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe
@URL = {{HOST}}/{{RESOURCE}}


### Create Justification Type
POST {{URL}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": "{{JUSTIFICATION_TYPE_ID}}",
  "name": "Tipo justificativa 2(anexo!!)",
  "shouldHaveAttachment": false
}

### List All Justification Types
GET {{URL}}/types
Content-Type: application/json
Authorization: Bearer {{JWT}}


### Delete Justification Type 
# @name delete-type
DELETE {{URL}}/type/{{JUSTIFICATION_TYPE_ID}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Update Justification Type 
PUT {{URL}}/types/{{JUSTIFICATION_TYPE_ID}}
rontent-Type: application/json
Authorization: Bearer {{JWT}}

{ 
  "shouldHaveAttachment": true
}

### Get JustificationAttachmentUrl 
GET {{URL}}/attachments/809cba83-dbc4-4bbb-8cd6-9f19f4387f97-shrek.jpg
Authorization: Bearer {{JWT}}
