@RESOURCE = solicitation/solicitations
@URL = {{HOST}}/{{RESOURCE}}
@DAY_OFF_SCHEDULE_ADJUSTMENT_SOLICITATION_ID =2b0f3c4d-5a1e-4b8f-9a7c-6d1e0f3b2c5d
@PAID_OVERTIME_SOLICITATION_ID = dc8e05b7-50c1-429c-8e2f-1bf9bf7925f2
@DAY_OFF_SOLICITATION_ID = 916f0a5b-0aec-4020-afe4-67b4b3fc57d8
@EXCEUSED_ABSENCE_SOLICITATION_ID = 77c46bfc-7cce-42fc-b1f6-3a752d77aede
@COLLABORATOR_ID = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe

### Create time punch adjustment solicitation
POST {{URL}}/time-punch-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{}

### List time punch adjustment solicitations
GET {{URL}}/time-punch-adjustment?page=1
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Aprove time punch adjustment solicitation
PUT {{URL}}/{{PAID_OVERTIME_SOLICITATION_ID}}/approve/time-punch-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Seu ponto foi ajustado!"
}

### Create paid overtime solicitation
POST {{URL}}/paid-overtime
Content-Type: application/json
Authorization: Bearer {{JWT}}

{}

### Aprove paid overtime solicitation
PUT {{URL}}/{{PAID_OVERTIME_SOLICITATION_ID}}/approve/paid-overtime
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Faça bom proveito dessa hora extra!"
}

### List paid overtime solicitations
GET {{URL}}/paid-overtime?page=1
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Create day off solicitation
POST {{URL}}/day-off
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "dayOff": "2025-05-31"
}

### List day off solicitations
GET {{URL}}/day-off?page=1
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Aprove day off solicitation
PUT {{URL}}/{{DAY_OFF_SOLICITATION_ID}}/approve/day-off
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Tenha seu dia de descanso!"
}

### Create excused absence Solicitation 
POST {{URL}}/excused-absence
Content-Type: application/json 
Authorization: Bearer {{JWT}}

{
  "absenceDate": "2025-04-27"
}

### List excused absence solicitations
GET {{URL}}/excused-absence?page=1
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Aprove excused absence solicitation
PUT {{URL}}/{{EXCEUSED_ABSENCE_SOLICITATION_ID}}/approve/excused-absence
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Você está perdoado!"
}

### Get All day off schedule adjustment solicitations 
GET {{URL}}/day-off-schedule-adjustment
Content-Type: application/json 
Authorization: Bearer {{JWT}}

### Create Day Off Schedule Adjustment Solicitation
POST {{URL}}/day-off-schedule-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "dayOffSchedule": {
    "workdaysCount": 20,
    "daysOffCount": 10,
    "daysOff": ["2025-04-05", "2025-04-10", "2025-04-15"]
  }
}

### Approve day off schedule adjustment solicitations
PUT {{URL}}/2b0f3c4d-5a1e-4b8f-9a7c-6d1e0f3b2c5d/approve/day-off-schedule-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Aprovado!,merece descansar banana!"
}


### Create Time Punch Adjustment Solicitation
POST {{URL}}/time-punch-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "time": "23:00",
  "period": "FIRST_CLOCK_IN",
  "workdayLogDate": "2025-04-05",
  "reason": "FORGOTTEN"
}

### Deny solicitation 
PATCH {{URL}}/{{DAY_OFF_SOLICITATION_ID}}/deny
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Não fui com a sua cara!"
}
