@RESOURCE = portal/solicitations
@URL = {{HOST}}/{{RESOURCE}}
@DAY_OFF_SCHEDULE_ADJUSTMENT_SOLICITATION_ID = 2b0f3c4d-5a1e-4b8f-9a7c-6d1e0f3b2c5d
@DAY_OFF_SOLICITATION_ID = c0b7618f-38b3-40e8-b2f3-1f67d2e2a26c
@EXCEUSED_ABSENCE_SOLICITATION_ID = 77c46bfc-7cce-42fc-b1f6-3a752d77aede
@WORK_LEAVE_SOLICITATION_ID = 4fc315d5-6c19-473c-8cd7-b2bcc097a5d7
@COLLABORATOR_ID = 56ab2a6d-39f7-4fba-a001-f33ccbe39dfe

### Create time punch adjustment solicitation
POST {{URL}}/time-punch-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{}

### List time punch adjustment solicitations
GET {{URL}}/time-punch-adjustment?page=1
Content-Type: application/json
Authorization: Bearer {{JWT}}


### Create day off solicitation
POST {{URL}}/day-off
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "dayOff": "2025-05-31"
}

### List day off solicitations
GET {{URL}}/day-off?page=1
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Aprove day off solicitation
PUT {{URL}}/{{DAY_OFF_SOLICITATION_ID}}/approve/day-off
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Tenha seu dia de descanso!"
}

### Create excused absence Solicitation 
POST {{URL}}/excused-absence
Content-Type: application/json 
Authorization: Bearer {{JWT}}

{
  "absenceDate": "2025-04-27"
}

### List excused absence solicitations
GET {{URL}}/excused-absence?page=1
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Aprove excused absence solicitation
PUT {{URL}}/{{EXCEUSED_ABSENCE_SOLICITATION_ID}}/approve/excused-absence
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Você está perdoado!"
}

### Create vacation solicitation 
POST {{URL}}/work-leave/vacation
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "startedAt": "2025-05-10",
  "endedAt": "2025-05-15"
}

### List vacation solicitations
GET {{URL}}/work-leave/vacation?page=1
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Create withdraw solicitation
POST {{URL}}/work-leave/withdraw
Content-Type: application/json 
Authorization: Bearer {{JWT}}

{
  "startedAt": "2025-05-31",
  "endedAt": "2025-06-01"
}

### List withdraw solicitations 
GET {{URL}}/work-leave/withdraw?page=1
Content-Type: application/json
Authorization: Bearer {{JWT}}

### Aprove work leave solicitation
PUT {{URL}}/{{WORK_LEAVE_SOLICITATION_ID}}/approve/work-leave
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Descance bastante"
}

### Get All day off schedule adjustment solicitations 
GET {{URL}}/day-off-schedule-adjustment
Content-Type: application/json 
Authorization: Bearer {{JWT}}

### Create day off schedule adjustment solicitation
POST {{URL}}/day-off-schedule-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "dayOffSchedule": {
    "workdaysCount": 6,
    "daysOffCount": 1,
    "daysOff": ["2025-05-11", "2025-05-12", "2025-05-13"]
  }
}

### Approve day off schedule adjustment solicitations
PUT {{URL}}/4a4137cf-29a7-49d0-82bd-b622c64ba731/approve/day-off-schedule-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Aprovado!,merece descansar banana!"
}

### Create time punch adjustment solicitation
POST {{URL}}/time-punch-adjustment
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "time": "23:00",
  "period": "FIRST_CLOCK_IN",
  "workdayLogDate": "2025-04-05",
  "reason": "FORGOTTEN"
}

### Deny solicitation 
PATCH {{URL}}/{{WORK_LEAVE_SOLICITATION_ID}}/deny
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "feedbackMessage": "Não fui com a sua cara!"
}

### Cancel solicitation 
PATCH {{URL}}/b221ab93-4f01-4333-a260-66db2344019f/cancel
Content-Type: application/json
Authorization: Bearer {{JWT}}

