@RESOURCE = portal/work-leave-calendar
@URL = {{HOST}}/{{RESOURCE}}

### Get work leave calendar
GET {{URL}}?year=2025&month=5&page=2&collaboratorName
Content-Type: application/json
Authorization: Bearer {{JWT}}