name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto assign reviewers
        uses: actions/github-script@v7
        with:
          script: |
            const author = context.payload.pull_request.user.login;
            const allMembers = ['kaufon', 'JohnPetros', 'EduardoKuwahara', '0thigs'];

            const getRandom = (arr, exclude = []) => {
              const filtered = arr.filter(x => !exclude.includes(x));
              return filtered[Math.floor(Math.random() * filtered.length)];
            };

            let reviewers = [];

            if (author === 'kaufon') {
              reviewers.push('JohnPetros');
              reviewers.push(getRandom(['EduardoKuwahara', '0thigs']));
            } else if (author === 'JohnPetros') {
              reviewers.push('kaufon');
              reviewers.push(getRandom(['EduardoKuwahara', '0thigs']));
            } else if (author === 'kukas' || author === '0thigs') {
              const potential = ['kaufon', 'JohnPetros', author === 'EduardoKuwahara' ? '0thigs' : 'EduardoKuwahara'];
              const first = getRandom(potential);
              const second = getRandom(potential.filter(x => x !== first));
              reviewers = [first, second];
            }

            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers
            });

